# Generated by Django 4.1.7 on 2023-02-26 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('credit_debt', models.FloatField(null=True)),
                ('amount_paid', models.FloatField(null=True)),
                ('amount_remaining', models.FloatField(null=True)),
            ],
        ),
    ]
