# Generated by Django 4.1.7 on 2023-02-26 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('credit_par_client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
        ),
    ]
